import { chromium } from 'playwright-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const root = path.resolve('storybook-static');
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.jpg': 'image/jpeg' };
const srv = http.createServer((q, s) => { let p = decodeURIComponent(q.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; const f = path.join(root, p); if (!fs.existsSync(f)) { s.writeHead(404); return s.end(); } s.writeHead(200, { 'content-type': mime[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(s); }).listen(6098);
const b = await chromium.launch({ executablePath: '/usr/bin/google-chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 900, height: 800 } });
const go = (id) => p.goto(`http://localhost:6098/iframe.html?id=${id}&viewMode=story`, { waitUntil: 'load' }).then(() => p.waitForSelector('.rumbo'));
const res = []; const ok = (n, c) => { res.push([n, !!c]); };
await go('components-folder-tabs--default');
await p.focus('.ftab[aria-selected="true"]'); await p.keyboard.press('ArrowRight');
ok('tabs: ArrowRight selects 2nd + focus', await p.evaluate(() => document.activeElement.getAttribute('aria-selected') === 'true' && document.activeElement.textContent.includes('Málaga')));
ok('tabs: panel swapped', await p.evaluate(() => document.querySelectorAll('.leg:not([hidden])').length === 1 && !document.querySelector('.leg:not([hidden])').textContent.includes('Week one')));
await p.keyboard.press('Home'); ok('tabs: Home', await p.evaluate(() => document.activeElement.textContent.includes('Lisbon')));
await go('components-accordion--single-open');
await p.click('.acc:nth-child(2) .acc__btn');
ok('accordion: click opens 2, closes 1 (single)', await p.evaluate(() => { const b = [...document.querySelectorAll('.acc__btn')].map(x => x.getAttribute('aria-expanded')); return b.join() === 'false,true,false'; }));
await p.focus('.acc:nth-child(2) .acc__btn'); await p.keyboard.press('ArrowDown');
ok('accordion: ArrowDown moves focus', await p.evaluate(() => document.activeElement.id.endsWith('-b2')));
await p.keyboard.press('Home'); ok('accordion: Home', await p.evaluate(() => document.activeElement.id.endsWith('-b0')));
await go('components-nav-drawer--interactive');
await p.click('[data-drawer-open]');
await p.waitForTimeout(500);
ok('drawer: opens, focus in Close', await p.evaluate(() => document.querySelector('.drawer').classList.contains('is-open') && document.activeElement.hasAttribute('data-drawer-close')));
await p.keyboard.press('Shift+Tab'); ok('drawer: Shift+Tab wraps to last', await p.evaluate(() => document.activeElement.classList.contains('btn')));
await p.keyboard.press('Tab'); ok('drawer: Tab wraps to first', await p.evaluate(() => document.activeElement.hasAttribute('data-drawer-close')));
await p.keyboard.press('Escape'); await p.waitForTimeout(500);
ok('drawer: Escape closes, inert, focus back on Menu', await p.evaluate(() => !document.querySelector('.drawer').classList.contains('is-open') && document.querySelector('.drawer').hasAttribute('inert') && document.activeElement.hasAttribute('data-drawer-open')));
await go('components-banner--dismissible'); await p.click('.banner__close'); ok('banner: dismiss hides', await p.evaluate(() => document.querySelector('.banner').hidden));
await go('components-chip-ticket-punch--group');
await p.focus('input[name=group]:checked'); await p.keyboard.press('ArrowRight');
ok('chip: radio arrow moves selection', await p.evaluate(() => document.querySelector('input[name=group]:checked')?.value === 'Not sure yet'));
await go('components-text-field--error');
ok('field: error visible + aria-invalid + described', await p.evaluate(() => { const i = document.querySelector('.tf__input'); const e = document.getElementById(i.getAttribute('aria-describedby').split(' ').pop()); return i.getAttribute('aria-invalid') === 'true' && !e.hidden && e.textContent.includes('valid email'); }));
await go('components-button--default'); await p.keyboard.press('Tab');
const ring = await p.evaluate(() => { const c = getComputedStyle(document.activeElement); return c.outlineStyle + ' ' + c.outlineWidth; }); ok('button: focus-visible ring 3px (' + ring + ')', /solid 3px/.test(ring));
await go('components-button--default');
const bh = await p.evaluate(() => document.querySelector('.btn').getBoundingClientRect().height); ok('button md height >= 48 (' + bh + ')', bh >= 48);
// reduced-motion
const pr = await b.newPage({ reducedMotion: 'reduce' }); await pr.goto('http://localhost:6098/iframe.html?id=components-button--default&viewMode=story'); await pr.waitForSelector('.btn');
ok('reduced motion: transition ~0', await pr.evaluate(() => parseFloat(getComputedStyle(document.querySelector('.btn')).transitionDuration) < 0.01));
res.forEach(([n, c]) => console.log(c ? 'PASS' : 'FAIL', n));
await b.close(); srv.close(); process.exit(res.every(r => r[1]) ? 0 : 1);
